version: '3.8'

services:
  app:
    build:
      context: .
      target: development
    container_name: kanban-board-app
    volumes:
      # プロジェクトルートを特定のサブディレクトリにマウントする方法
      - ./src:/app/src
      - ./index.html:/app/index.html
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.app.json:/app/tsconfig.app.json
      - ./tsconfig.node.json:/app/tsconfig.node.json
      - ./postcss.config.js:/app/postcss.config.js
      - ./tailwind.config.js:/app/tailwind.config.js
      - ./vite.config.ts:/app/vite.config.ts
      - ./server.js:/app/server.js
      - ./.env:/app/.env
      - ./docker/mariadb:/app/docker/mariadb
      - ./docker/nginx.conf:/app/docker/nginx.conf
      # 永続化するデータボリューム
      - node_modules_volume:/app/node_modules
    ports:
      - "5173:5173"
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=kanban
      - DB_PASSWORD=kanban_password
      - DB_NAME=kanban_board
    # ログを標準出力に表示する設定に変更
    tty: true
    stdin_open: true
    command: >
      sh -c "
        node server.js &
        VITE_CJS_IGNORE_WARNING=true npm run dev -- --host
      "
    depends_on:
      - db

  db:
    image: mariadb:10.11
    container_name: kanban-board-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: kanban_board
      MYSQL_USER: kanban
      MYSQL_PASSWORD: kanban_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./docker/mariadb/init:/docker-entrypoint-initdb.d

volumes:
  mariadb_data:
  node_modules_volume: